### ISSUE TITLE
:memo: [Docs] 0410 TODO

### ISSUE THREAD

**Issue by anso33** [cozy-for-mom/cozy-for-mom-backend#154]
> TODO

- [ ] 최근 검색어 API 만들기  (10개)
- [ ] 검색결과 댓글순대로 안오는 것 같음
- [ ] DB에 코지로그 content 바꿔놓기

> Description
